### ISSUE TITLE
fix: address issue of not being able to read other users' public entries

### ISSUE THREAD

**Issue by boyeonihn** [boyeonihn/manyaday#18]

**Comment by boyeonihn** [comment]
@eunjae-lee 

So I was thinking about this current problem (i.e. RLS policy of public.profiles is limiting user access to other user's public entries), and realized another thing. If down the line I want to create a /[username] page where users can view another user's profile (e.g. like twitter.com/boyeonihn), this route would also have issues since useUserByUsername is trying to access `public.profile` with this current RLS policy. 

The only idea that I have right now (coming from a person who isn't well-versed in supabase quite yet), was having two public tables - one is `users`, where more sensitive/personal information that only the user has access to is stored such as email address, first and last name), and `profiles` table, where more public info like avatar url, username, public profile content is stored. This way, for `profiles` table I can allow read access to all (public profile information is readable by everyone). 

Not totally sure if creating a separate users & profiles table is too overkill and there's actually a simpler way to do this.

**Comment by eunjae-lee** [comment]
@boyeonihn Okay, after reading this, I've got an idea. What if we keep the current `auth.users` and `public.profiles` tables as-is, but we add `is_public` column to `public.profiles` table. So `/[username]` page works for public profiles. And `/[username]/[mmdd]` works for public profile AND public entries. What do you think? There can be an explicit setting on the profile setup page that says "is this profile publicly visible?", but we could also later have a "make this entry public" button, and if it's clicked, we could show "this will make your profile visible, too. you okay?"

If we decide to go with that flow, then we need to slightly update our RLS policy, and that's it. So this is a situation that product planning is deciding technical requirements :)

**Comment by boyeonihn** [comment]
@eunjae-lee 
Woah this is an interesting approach. So to summarize, with this product planning in mind (& to make sure I am understanding the impact of this potential flow):

me, logged in as username `boyeonihn`, and there is `eunjae-lee` whose profile IS public, `sorok` whose profile is private. 
- would be able to visit `/boyeonihn` since RLS would allow user to view own `public.profiles` object
- would be able to visit `/boyeonihn/[mmdd]` since it is owned by me
- would be able to visit `/eunjae-lee` (since `public.profiles` would have `is_public` as `true`)
- would also be able visit `/eunjae-lee/0502` to view eunjae's posts written on May 2nd that are marked `public` (in public.entries is_public column). 
- would NOT be able to visit `/eunjaelee/0501` if all of eunjae's May 1st posts are marked `private`
- `boyeonihn` would not be able to access `/sorok` since sorok user's `is_public` in public.profiles is `false`
- however, if `sorok` later writes an entry and makes the entry public and submits -> this would also make `sorok`'s profile visible (so from then on `boyeonihn` would be able to access `/sorok` profile page. But sorok would still be able to make certain entries private even with a public profile. 

Did I get the flow correctly? I had to make it concrete with examples to double check. If my understanding is correct, I kinda like this approach a lot!

**Comment by eunjae-lee** [comment]
@boyeonihn yes, that's exactly what I had in mind!

**Comment by boyeonihn** [comment]
@eunjae-lee 

Great! So next steps would be:
- creating `is_public` column in `public.profiles` table
- modifying the RLS policy. So I just realized that my `public.entries` table is kind of already setup I thiiink in the direction we're trying to head towards for `public.profiles`too? `entries` has a`select/read` RLS policy where "users can view own entries and other users' public entries`
![CleanShot 2024-05-07 at 18 29 29](https://github.com/boyeonihn/manyaday/assets/95451902/7308509c-19ca-4ed2-9dbc-1c6efdedff17)

- would this be basically how I would be modifying the RLS policy for `public.profiles`?  ("users can view own profiles and other users' public profiles")

**Comment by eunjae-lee** [comment]
@boyeonihn 

* yes
* Yes!
* YES!!!
